import { useState, useRef } from 'react'
import SignatureCanvas from 'react-signature-canvas'
import { jsPDF } from 'jspdf'
import { FileDown, PenLine, CheckCircle, Clock, Image, Trash2, Plus } from 'lucide-react'
import { MOCK_WORK_ORDERS, MOCK_EMPLOYEES } from '../lib/mockData'
import { useOrg } from '../contexts/OrgContext'
import clsx from 'clsx'

const STATUS = {
  pending:   { label: '待執行', badge: 'badge-yellow', icon: Clock },
  completed: { label: '已完成', badge: 'badge-green',  icon: CheckCircle },
}

function SignModal({ workOrder, onClose }) {
  const sigRef = useRef(null)
  const [signed, setSigned] = useState(false)

  const handleClear = () => { sigRef.current?.clear(); setSigned(false) }

  const handleSave = () => {
    if (sigRef.current?.isEmpty()) {
      alert('請先完成簽名')
      return
    }
    const dataUrl = sigRef.current.toDataURL('image/png')
    // In production: upload dataUrl to Firebase Storage
    console.log('Signature captured, upload to Firebase Storage:', dataUrl.substring(0, 50))
    setSigned(true)
    setTimeout(onClose, 800)
  }

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md p-6">
        <h2 className="text-lg font-bold text-gray-900 mb-1">客戶電子簽名</h2>
        <p className="text-sm text-gray-500 mb-4">派工單：{workOrder.siteName} — {workOrder.date}</p>

        <div className="border-2 border-dashed border-gray-300 rounded-xl bg-gray-50 relative">
          {signed ? (
            <div className="h-48 flex items-center justify-center text-green-600">
              <CheckCircle size={40} />
            </div>
          ) : (
            <SignatureCanvas
              ref={sigRef}
              canvasProps={{ width: 400, height: 190, className: 'rounded-xl w-full' }}
              backgroundColor="rgb(249,250,251)"
            />
          )}
        </div>

        <div className="flex justify-between gap-3 mt-4">
          <button className="btn-secondary" onClick={handleClear}>
            <Trash2 size={14} /> 清除
          </button>
          <div className="flex gap-2">
            <button className="btn-secondary" onClick={onClose}>取消</button>
            <button className="btn-primary" onClick={handleSave}>
              <CheckCircle size={14} /> 確認簽名
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

function exportPDF(wo) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  // Header
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text('Work Order / Cleaning Service Report', 20, 25)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(`Site: ${wo.siteName}`, 20, 38)
  doc.text(`Date: ${wo.date}`, 20, 44)
  doc.text(`Status: ${STATUS[wo.status]?.label}`, 20, 50)

  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Material List', 20, 65)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  wo.materialList?.forEach((m, i) => {
    doc.text(`  • ${m}`, 20, 73 + i * 7)
  })

  const employees = MOCK_EMPLOYEES.filter(e => wo.employeeIds?.includes(e.id))
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Assigned Team', 120, 65)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  employees.forEach((e, i) => {
    doc.text(`  • ${e.name}`, 120, 73 + i * 7)
  })

  doc.setFontSize(9)
  doc.setTextColor(150)
  doc.text('Generated by Cleaning ERP System', 20, 280)

  doc.save(`work-order-${wo.id}.pdf`)
}

export default function WorkOrdersPage() {
  const { activeOrgId } = useOrg()
  const [signTarget, setSignTarget] = useState(null)
  const [statusFilter, setStatus]   = useState('all')

  const orders = MOCK_WORK_ORDERS
    .filter(wo => wo.orgId === activeOrgId)
    .filter(wo => statusFilter === 'all' || wo.status === statusFilter)

  return (
    <div className="max-w-4xl mx-auto space-y-5">
      {/* Toolbar */}
      <div className="flex flex-wrap items-center gap-3">
        <select className="input w-auto" value={statusFilter} onChange={e => setStatus(e.target.value)}>
          <option value="all">全部</option>
          <option value="pending">待執行</option>
          <option value="completed">已完成</option>
        </select>
        <div className="flex-1" />
        <button className="btn-primary">
          <Plus size={16} /> 手動建立派工單
        </button>
      </div>

      {/* Work order cards */}
      <div className="space-y-4">
        {orders.map(wo => {
          const StatusIcon = STATUS[wo.status]?.icon || Clock
          const emps = MOCK_EMPLOYEES.filter(e => wo.employeeIds?.includes(e.id))

          return (
            <div key={wo.id} className="card overflow-hidden">
              {/* Top bar */}
              <div className="flex items-center gap-3 px-4 py-3 bg-gray-50 border-b border-gray-100">
                <StatusIcon size={16} className={wo.status === 'completed' ? 'text-green-600' : 'text-amber-500'} />
                <span className="font-semibold text-gray-900 flex-1">{wo.siteName}</span>
                <span className={`badge ${STATUS[wo.status]?.badge}`}>{STATUS[wo.status]?.label}</span>
                <span className="text-sm text-gray-500">{wo.date}</span>
              </div>

              <div className="p-4 grid grid-cols-1 sm:grid-cols-2 gap-4">
                {/* Left */}
                <div className="space-y-3">
                  <div>
                    <p className="text-xs text-gray-500 mb-1">施工人員</p>
                    <div className="flex flex-wrap gap-1">
                      {emps.map(e => <span key={e.id} className="badge badge-blue">{e.name}</span>)}
                    </div>
                  </div>
                  {wo.notes && (
                    <div>
                      <p className="text-xs text-gray-500 mb-1">特殊備註</p>
                      <p className="text-sm text-gray-700 bg-amber-50 rounded-lg px-3 py-2">{wo.notes}</p>
                    </div>
                  )}
                  <div>
                    <p className="text-xs text-gray-500 mb-1">建議攜帶物料</p>
                    <ul className="space-y-0.5">
                      {wo.materialList?.map((m, i) => (
                        <li key={i} className="text-sm text-gray-700 flex items-center gap-1.5">
                          <span className="w-1 h-1 bg-brand-400 rounded-full shrink-0" />{m}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                {/* Right */}
                <div className="space-y-3">
                  <div>
                    <p className="text-xs text-gray-500 mb-1">工作時段</p>
                    <p className="text-sm text-gray-700">
                      {wo.actualStart ? `${wo.actualStart} – ${wo.actualEnd}` : '—'}
                    </p>
                  </div>
                  <div>
                    <p className="text-xs text-gray-500 mb-1">現場照片</p>
                    <div className="flex gap-2">
                      {wo.photos.length === 0
                        ? <span className="text-xs text-gray-400">尚無照片</span>
                        : wo.photos.map((p, i) => (
                            <img key={i} src={p} className="w-12 h-12 rounded-lg object-cover" alt="" />
                          ))
                      }
                    </div>
                  </div>
                  <div>
                    <p className="text-xs text-gray-500 mb-1">客戶簽名</p>
                    {wo.signedAt
                      ? <span className="badge badge-green"><CheckCircle size={11} className="mr-1" /> 已簽收 {wo.signedAt}</span>
                      : <span className="badge badge-gray">未簽收</span>
                    }
                  </div>
                </div>
              </div>

              {/* Actions */}
              <div className="flex gap-2 px-4 pb-4">
                {wo.status === 'pending' && (
                  <button className="btn-secondary text-xs" onClick={() => setSignTarget(wo)}>
                    <PenLine size={13} /> 請客戶簽名
                  </button>
                )}
                <button className="btn-secondary text-xs" onClick={() => exportPDF(wo)}>
                  <FileDown size={13} /> 直接下載 PDF
                </button>
              </div>
            </div>
          )
        })}
      </div>

      {/* Signature modal */}
      {signTarget && (
        <SignModal workOrder={signTarget} onClose={() => setSignTarget(null)} />
      )}
    </div>
  )
}
